### ISSUE TITLE
Cache responses

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/pytest-check-links#11]
Taking inspiration from [brok](https://github.com/smallhadroncollider/brok), I think we should have a cache that is persisted in CI, and only check links that haven't been checked in 24hrs (settable).  This will cut down on our DDOS-ing.

**Comment by bollwyvl** [comment]
This is a very good idea, and brok looks cool!

Rather than tackling cache invalidation, my quick take would be to:
- use `requests` and a `requests.Session`
  - but still not cache, by default
- add an option `--check-links-cache <cache name>`
    - which would trigger a dependency on `requests-cache` which Just Works :tm: with sqlite (by default)
  - replace the `requests.Session` with a `requests_cache.CachedSession`
- add options for all the other shiny parts that wouldn't have to be written from scratch, e.g.  
  - `--check-links-cache-expire <seconds>`
  - `--check-links-cache-backend <backend>`
  - `--check-links-cache-option <key>:<value>` for all the other stuff the backsend support

If that sounds reasonable, I'd be happy to take a look at it!

**Comment by blink1073** [comment]
That sounds fantastic, @bollwyvl, please do!
